; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#include "CodeDependencies.iss"

; ==================== 应用基本信息 ====================
#define MyAppName "SimpleCollectionHub"
; #define MyAppVersion "0.0.1.0"
#define MyAppPublisher "美昂兴电子技术有限公司"
#define MyAppCompanyName "MayonX"
#define MyAppURL "https://mayonx.com/"
#define MyAppExeName "SimpleCollectionHub.exe"
#define MyAppId "{{52B280AB-23E4-4BCE-B73C-C2EE53C9799A}"
#define FileDescription "SimpleCollectionHub Installer (Trial)"
#define FileVersion GetDateTimeString('yyyy.mm.dd.HHnn', '', '')
#define CopyrightYear "2026"

; ==================== 构建产物路径 ====================
; 相对 Installer 脚本目录；切换发布目录只改这一处
#define BuildOutputDir ".\..\bin\Release - Protected\net8.0-windows"
#define MainExePath BuildOutputDir + "\" + MyAppExeName
#define MyAppVersion GetFileVersion(MainExePath)

; ==================== 安装包输出 ====================
#define SetupOutputDir ".\Setup Files"
#define SetupOutputBaseFilename MyAppName + "_V" + MyAppVersion + "_Win64_Installer"

; ==================== .NET Desktop 运行时依赖 ====================
#define DotNetDesktopInstaller "dotnet80desktop_x64.exe"
#define DotNetDesktopInstallerSource ".\Prerequisites\" + DotNetDesktopInstaller

; ==================== 用户数据目录（卸载可选删除） ====================
; 对应程序内 FolderConfig.AppFolder = LocalAppData\CompanyName\AppName
#define MyAppDataDir "{localappdata}\" + MyAppCompanyName + "\" + MyAppName

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

VersionInfoVersion={#FileVersion}
VersionInfoCompany={#MyAppCompanyName}
VersionInfoDescription={#FileDescription}
VersionInfoCopyright=Copyright (C) {#CopyrightYear} {#MyAppPublisher}


DefaultDirName={autopf}\{#MyAppCompanyName}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=no
DisableProgramGroupPage=yes
; LicenseFile=.\License.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#SetupOutputDir}
OutputBaseFilename={#SetupOutputBaseFilename}
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

#include "UninstallEx_Languages.iss"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
; Name: "uninstshortcut"; Description: "{cm:CreateUninstallShortcut}"; GroupDescription: "{cm:AdditionalIcons}"

[InstallDelete]
; 1. 删除指定的文件夹（包括其内部所有的文件和子文件夹）
Type: filesandordirs; Name: "{app}\runtimes"
Type: filesandordirs; Name: "{app}\en"
Type: filesandordirs; Name: "{app}\zh"
Type: filesandordirs; Name: "{app}\zh-Hans"
; Type: filesandordirs; Name: "{app}\Properties"

; 2. 通过通配符删除目标目录下所有的 .dll 和 .pdb 文件
; 注意：这只会删除 {app} 根目录下的文件，不会影响前面已经删除过的子文件夹
Type: files; Name: "{app}\*.dll"
Type: files; Name: "{app}\*.pdb"
Type: files; Name: "{app}\*.exe"

[Files]
Source: "{#BuildOutputDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#BuildOutputDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

Source: "{#DotNetDesktopInstallerSource}"; Flags: dontcopy noencryption

[Icons]
Name: "{autoprograms}\{#MyAppCompanyName}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; WorkingDir: "{app}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function InitializeSetup: Boolean;
begin
  ExtractTemporaryFile('{#DotNetDesktopInstaller}');
  
  Dependency_AddDotNet80Desktop;

  Result := True;
end;


#include "UninstallEx.iss"